workflows:
  shorebird_ios_release:
    name: Shorebird iOS Release
    environment:
      flutter: stable
      xcode: latest
      vars:
        SHOREBIRD_TOKEN: Encrypted(...) # já configurado no painel do Codemagic
    scripts:
      - name: Recria arquivos iOS (incluindo Podfile)
        script: flutter create .
      - name: Install Shorebird CLI
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
      - name: Add Shorebird to PATH
        script: |
          echo 'export PATH="$HOME/.shorebird/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc
      - name: Shorebird login (CI)
        script: |
          echo "$SHOREBIRD_TOKEN" | shorebird login --ci
      - name: Shorebird release iOS
        script: |
          shorebird release ios
    artifacts:
      - build/ios/ipa/*.ipa